### ISSUE TITLE
Video availability

### ISSUE THREAD

**Issue by sidsvash26** [Eric-Wallace/interpretability-tutorial-emnlp2020#1]
Hi,

I attended the live session but couldn't go through the entire session at the time. Is it possible to access the video anywhere? I logged in to the EMNLP site but there's no URL for the video. 

Thanks

**Comment by cristianvasquez** [comment]
A video would be great!

**Comment by Eric-Wallace** [comment]
Video is now live here https://www.youtube.com/watch?v=gprIzglUW1s

**Comment by cristianvasquez** [comment]
Thanks @Eric-Wallace !
